package com.simon.cloud.word.urp.mapper;

import com.simon.cloud.word.api.entities.UrpLogin;
import com.simon.cloud.word.api.entities.UrpLoginExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface UrpLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    long countByExample(UrpLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    int deleteByExample(UrpLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    int insert(UrpLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    int insertSelective(UrpLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    List<UrpLogin> selectByExample(UrpLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    UrpLogin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") UrpLogin record, @Param("example") UrpLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    int updateByExample(@Param("record") UrpLogin record, @Param("example") UrpLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    int updateByPrimaryKeySelective(UrpLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_login
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    int updateByPrimaryKey(UrpLogin record);
}