package com.simon.cloud.word.api.entities;

import java.util.Date;

public class UrpLogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_login.id
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_login.user_id
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_login.login_name
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_login.login_password
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    private String loginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_login.login_type
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    private String loginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_login.add_time
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_login.app_key
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    private String appKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_login.id
     *
     * @return the value of urp_login.id
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_login.id
     *
     * @param id the value for urp_login.id
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_login.user_id
     *
     * @return the value of urp_login.user_id
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_login.user_id
     *
     * @param userId the value for urp_login.user_id
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_login.login_name
     *
     * @return the value of urp_login.login_name
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_login.login_name
     *
     * @param loginName the value for urp_login.login_name
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_login.login_password
     *
     * @return the value of urp_login.login_password
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_login.login_password
     *
     * @param loginPassword the value for urp_login.login_password
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_login.login_type
     *
     * @return the value of urp_login.login_type
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public String getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_login.login_type
     *
     * @param loginType the value for urp_login.login_type
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public void setLoginType(String loginType) {
        this.loginType = loginType == null ? null : loginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_login.add_time
     *
     * @return the value of urp_login.add_time
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_login.add_time
     *
     * @param addTime the value for urp_login.add_time
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_login.app_key
     *
     * @return the value of urp_login.app_key
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_login.app_key
     *
     * @param appKey the value for urp_login.app_key
     *
     * @mbg.generated Thu Oct 25 09:38:48 CST 2018
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }
}